### ISSUE TITLE
Distancia Levenstein

### ISSUE THREAD

**Issue by DinoThor** [DinoThor/alt_project#1]
### Archivo **distancias.py** -- Métodos a compeltar:

- levenshtein
- levenshtein_edicion
- levenshtein_reduccion

**Comment by DinoThor** [comment]
HECHO -- Reducción coste espacial levenshtein

**Comment by DinoThor** [comment]
Starting at the bottom-rightmost cell, and working our way backward toward 
the top left.

For each "backward" step, consider the 3 cells directly adjacent to the current
cell   (in the left, top or left+top directions)

   if the value in the diagonal cell (going up+left) is smaller or equal to the
      values found in the other two cells
   AND 
      if this is same or 1 minus the value of the current cell 
   then  "take the diagonal cell"
         if the value of the diagonal cell is one less than the current cell:
            Add a SUBSTITUTION operation (from the letters corresponding to
            the _current_ cell)
         otherwise: do not add an operation this was a no-operation.

   elseif the value in the cell to the left is smaller of equal to the value of
       the of the cell above current cell
   AND 
       if this value is same or 1 minus the value of the current cell 
   then "take the cell to left", and
        add an INSERTION of the letter corresponding to the cell
   else
       take the cell above, add
       Add a DELETION operation of the letter in 's string'

**Comment by DinoThor** [comment]
Levenshtein_edición funcional con 2 pruebas de la batería de test. Falta revisarlo

**Comment by DinoThor** [comment]
HECHO -- levenshtein threshold

**Comment by dmesmar** [comment]
también está acabada levenshtein edición que lo acabo de subir
